### ISSUE TITLE
Github Action workflow not installing R packages

### ISSUE THREAD

**Issue by shbrainard** [miraisolutions/rTRhexNG#4]
Hi there,

I'm trying to use your .yml file to automate deployment of an app of mine to shinyapps.io, but get the following error every time it's triggered by a push.  It runs fine through to "Query dependencies" and then:
```

Run install.packages("remotes")
Installing package into ‘/home/runner/work/_temp/Library’
(as ‘lib’ is unspecified)
Warning: Warning: unable to access index for repository /src/contrib:
  cannot open URL '/src/contrib/PACKAGES'

trying URL 'https://cloud.r-project.org/src/contrib/remotes_2.4.0.tar.gz'
Content type 'application/x-gzip' length 149836 bytes (146 KB)
==================================================
downloaded 146 KB

* installing *source* package ‘remotes’ ...
** package ‘remotes’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (remotes)

The downloaded source packages are in
	‘/tmp/RtmpEq9sEE/downloaded_packages’
Error: Error in read.dcf(path) : cannot open the connection
Calls: saveRDS ... load_pkg_description -> read_dcf -> colnames -> is.data.frame -> read.dcf
In addition: Warning message:
In read.dcf(path) :
  cannot open compressed file '/home/runner/work/payroll_shiny/payroll_shiny/DESCRIPTION', probable reason 'No such file or directory'
Execution halted
Error: Process completed with exit code 1.
```

Let me know if you have any thoughts on what might be causing this.

Thanks!
Scott

**Comment by riccardoporreca** [comment]
@shbrainard, I recommend referring to a section of a technical guide we have on the topic, with up-to-date instructions and examples: https://mirai-solutions.ch/techguides/github-actions.html, and in particular https://mirai-solutions.ch/techguides/github-actions.html#complete-wfs-use-gh-action

You can consider following up in the corresponding repository https://github.com/miraisolutions/techguides/, and in case please provide pointers to your project / failing workflow, as from an output like the one above there isn't much we could guess.

Closing this issue as it is not rTRhexNG-specific.

**Comment by shbrainard** [comment]
Thanks!  This was actually just addressed and fixed in a recent path to r-lib: https://github.com/r-lib/actions/issues/383
